config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  

  resources :enrollments do 
    get :my_students, on: :collection  
  end

  resources :courses do 
    member do 
      get :analytics
      get :approve
      get :unapprove
    end
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons do 
      put :sort
      member do 
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]

  namespace :charts do 
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses = Course.all.limit(3)
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
  end

  def activity
    if current_user.has_role?(:admin) 
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "You are not authorized to access this page!"
    end
  end

  def analytics
    if current_user.has_role?(:admin) 
      # @users = User.all 
      # @enrollments = Enrollment.all 
      # @courses = Course.all 
    else
      redirect_to root_path, alert: "You are not authorized to access this page!"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do 
  Coursera 
  \|
  Activity
%h2
  .text-center
    Activity 
    .badge.badge-info 
      = @activities.count

%p
%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      -# = activity.id
      = activity.created_at.strftime('%d-%m-%Y %H:%m') 
      (#{time_ago_in_words(activity.created_at)})
      = model_label(activity.trackable_type)
      = activity.trackable_type 
      -# = activity.trackable_id 
      - if activity.trackable_type == "Lesson"
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          Lesson was deleted 
      - else 
        = link_to activity.trackable, activity.trackable
      = activity.key 
      = crud_label(activity.key.match(/\.(.*)/)[1])
      by
      -# = activity.owner 
      = link_to activity.owner, user_path(activity.owner) 
      - if activity.parameters.any?
        = activity.parameters 
%br
!= pagy_bootstrap_nav(@pagy)
%br 

app/views/home/analytics.html.haml
%h3.text-center
  Users created per day
-# = line_chart @users.group_by_day(:created_at).count
= line_chart charts_users_per_day_path

%br
%h3.text-center
  Enrollments created per day
-# = column_chart @enrollments.group_by_day(:created_at).count
= column_chart charts_enrollments_per_day_path

%br 
%h3.text-center 
  Course popularity 
-# = pie_chart @courses.group(:enrollments_count).count
-# = pie_chart @enrollments.joins(:course).group(:'courses.title').count
-# = bar_chart @enrollments.joins(:course).group(:'courses.title').count
= pie_chart charts_course_popularity_path
= bar_chart charts_course_popularity_path

%br 
%h3.text-center 
  Most paid courses
= bar_chart charts_money_makers_path
%br 

app/views/home/index.html.haml
- content_for :title do 
  Coursera 
  \|
  Online Courses - Learn Anything, On Your Schedule 

.jumbotron 
  .display-4
    What do you want to learn today?

    .p-4 
  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group 
        = f.search_field :title_cont, placeholder: "Find a course", class: 'form-control form-control-sm', style: 'float: left; width: 250px'
        %span.input-group-append 
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}

  -# .form-inline.my-2.my-lg-0
  -#   = form_tag(courses_path, method: :get) do 
  -#     .input-group 
  -#       = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Find a course", class: 'form-control-sm', style: 'width: 250px'
  -#       %span.input-group-append
  -#         %button.btn.btn-primary.btn-sm{:type => "submit"}
  -#           %span.fa.fa-search{"aria-hidden" => "true"}

.p-4 

.card-group 
  .card.card-body 
    %h1
      .fa.fa-graduation-cap 
    = Course.count
    online courses 
    .row 
    Explore a veriety of fresh topics 
  .card.card-body 
    %h1
      .fa.fa-chalkboard-teacher 
    = Course.distinct.count(:user_id)
    expert instructors 
    .row 
    Find the right instructor for you
  .card.card-body 
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners 
    .row 
    Join the knowledge sharing community 
  .card.card-body 
    %h1
      .fa.fa-infinity
    = Course.count
    Lifetime access 
    .row 
    Learn on your schedule


%hr

- if current_user
  %h2
    .fa.fa-user-graduate
    Continue Learning 
  .card-columns 
    - @purchased_courses.each do |course|
      = render 'courses/course', course: course 
  .text-right 
    = link_to 'All my purchased courses', purchased_courses_path 

%hr
%h2
  .fa.fa-chart-line
  Popular courses 
.card-columns 
  - @popular.each do |course|
    = render 'courses/course', course: course 
.text-right 
  = link_to 'More popular courses', courses_path(courses_search: {s: 'enrollments_count desc'})

%hr
%h2
  .fa.fa-star
  Top rated courses 
.card-columns 
  - @top_rated.each do |course|
    = render 'courses/course', course: course 
.text-right 
  = link_to 'Best rated courses', courses_path(courses_search: {s: 'average_rating desc'})

%hr
%h2
  .fa.fa-clock
  Latest courses 
.card-columns 
  - @latest.each do |course|
    = render 'courses/course', course: course 
.text-right 
  = link_to 'More new courses', courses_path(courses_search: {s: 'created_at desc'})

%hr
%h2
  .fa.fa-comment
  What our students have to say 
.card-columns 
  - @latest_good_reviews.each do |enrollment|
    = render 'enrollments/enrollment', enrollment: enrollment 