config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  

  resources :enrollments do 
    get :my_students, on: :collection  
  end

  resources :courses do 
    member do 
      get :analytics
      get :approve
      get :unapprove
    end
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons do 
      put :sort
      member do 
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]

  namespace :charts do 
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:show]
  before_action :set_course, only: %i[ show edit update destroy approve unapprove analytics ]

  def index
    # if params[:title]
    #   @courses = Course.where('title ILIKE ?', "%#{params[:title]}%")
    # else 
    #   # @courses = Course.all

    #   # @q = Course.ransack(params[:q])
    #   # @courses = @q.result.includes(:user)
    # end 
    @ransack_path = courses_path

    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
  end

  def purchased
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def created 
    @ransack_path = created_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def unapproved
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user))
    render 'index'
  end

  def approve 
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: "Course approved and visible!"
  end

  def unapprove 
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course unapproved and hidden!"
  end

  def analytics
    authorize @course, :owner?
  end

  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @enrollments_with_review = @course.enrollments.reviewed
  end

  def new
    @course = Course.new
    authorize @course
  end

  def edit
    authorize @course 
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to @course, alert: 'Course has enrollments. Can not be destroyed.'
    end
  end

  private
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price, :language, :level, :published, :avatar)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user 
        link_to "You created this course. View analytics", course_path(course)
      elsif course.enrollments.where(user: current_user).any? 
        link_to course_path(course) do 
          # "You bought this course. keep learning" +
          "<i class='fa fa-spinner'></i>".html_safe + " " +
          number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: 'btn btn-success'
      else
        link_to "Free", new_course_enrollment_path(course), class: 'btn btn-success'
      end
    else
      link_to "Check price", new_course_enrollment_path(course), class: "btn btn-md btn-success"
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do 
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='text-dark fa fa-question'></i>".html_safe + " " +
            'Add a Review'
          end
        else
          link_to enrollment_path(user_course.first) do 
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='fa fa-check'></i>".html_safe + " " +
            'Thanks for reviewing! Your Review'
          end
        end
      end
    end
  end

end

app/views/courses/_course.html.haml
.card 
  .card-header 
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course) 
  - if course.avatar.attached?
    .card-img-top
      = image_tag course.avatar, width: "100%";
      -# = image_tag course.avatar.variant(resize_to_limit: [100, 100])
  .card-body 
    %small= simple_format(course.short_description) 
  .card-footer 
    .text-center
      = enrollment_button(course)
      .row
      = review_button(course)
  .card-footer
    .row 
      .col-md-6
        .text-warning.fa.fa-star 
        = course.average_rating 
        -# Enrollments count:
        -# = course.enrollments.count 
        (
        .fa.fa-user-graduate
        = course.enrollments_count
        )
        .fa.fa-tasks
        = course.lessons_count
      .col-md-6
        .text-right
          .fa.fa-chalkboard-teacher
          = link_to course.user.username, user_path(course.user)
    
          
  -# .card-footer 
  -#   .row 
  -#     .col-md-6 
  -#       .fa.fa-globe-africa
  -#       = course.language
  -#     .col-md-6 
  -#       .text-right
  -#         .fa.fa-signal 
  -#         = course.level
  -# .card-footer
  -#   .row 
  -#     .col-md-6
  -#       .far.fa-clock
  -#       = course.created_at.strftime('%d-%b-%Y')
  -#     .col-md-6
  -#       .text-right
  -#         .fa.fa-chalkboard-teacher
  -#         = link_to course.user.username, user_path(course.user)
  - if current_user
    - if policy(course).owner?
      .card-footer
        = link_to 'Add lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-sm btn-primary'
        = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' # if policy(course).edit?
        - if policy(course).destroy?
          = button_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger', style: 'display: inline-block' # if policy(course).destroy?
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-info' do 
          .fa.fa-chart-bar 
          Analtycs 

    - if policy(course).admin_or_owner?
      .card-footer 
        - if course.published?
          .badge.badge-success published 
        - else 
          .badge.badge-danger unpublished
        - if course.approved?
          .badge.badge-success approved 
        - else 
          .badge.badge-danger unapproved
    - if policy(course).approve?
      .card-footer 
        - if course.approved?
          = link_to 'unapprove', unapprove_course_path(course), method: :get, class: 'btn btn-sm btn-danger'
        - else 
          = link_to 'approve', approve_course_path(course), method: :get, class: 'btn btn-sm btn-success'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    %br
    -# = f.label :avatar
    - if @course.avatar.attached?
      = image_tag @course.avatar, width: "200px";
      .row
      = @course.avatar.filename 
    -# = f.file_field :avatar
    -# %small= f.error :avatar, class: 'text-danger'
    = f.input :avatar

    .row
    = f.label :description
    = f.rich_text_area :description
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    -# = f.input :language, collection: ["English", "Polish", "Spanish"]
    = f.input :language, collection: Course.languages, include_blank: true
    -# = f.input :level, collection: ["Beginner", "Intermediate", "Advanced"]
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price
    %p
    = f.input :published 

  .form-actions
    = f.button :submit

app/views/courses/analytics.html.haml
- content_for :title do 
  Coursego 
  |
  = @course.title
  Analtycs 

= link_to 'Courses', courses_path 
|
= link_to course_path(@course) do 
  .fa.fa-graduation-cap 
  = @course.title 
|
= link_to analytics_course_path(@course) do 
  .fa.fa-chart-bar 
  Analtycs 

%h4.text-center 
  Analtycs for #{@course.title}

Enrollments per day, quantity 
= line_chart @course.enrollments.group_by_day(:created_at).count 

Enrollments per day, revenue
= line_chart @course.enrollments.group_by_day(:created_at).sum(:price)

Unique user views (how many unique users viewed the lesson) 
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count 

Impressions per lesson (how many time the lesson was opened) 
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions) 

app/views/courses/edit.html.haml
- content_for :title do 
  Coursera 
  \|
  Editing
  = @course.title
.card 
  .card-header
    %h2
      .fa.fa-graduation-cap
      Editing course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do 
  Coursera 
  \|
  = action_name.humanize 
  courses 

%h2
  .text-center
    = action_name.humanize 
    Courses 
    .badge.badge-info 
      = @courses.count
%p

.row 
  .col-md-2 
    .form-inline
      -# = search_form_for @q do |f|
      = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
        = f.label :title
        = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
        = f.label :description
        = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
        -# = f.search_field :language_cont, placeholder: 'Language', class: 'form-control form-control-sm'
        = f.label :language
        = f.select :language_cont, Course.languages, include_blank: true
        -# = f.search_field :level_cont, placeholder: 'Level', class: 'form-control form-control-sm'
        .row
        = f.label :level
        = f.select :level_cont, Course.levels, include_blank: true
        = f.label :price
        = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
        = f.label :teacher
        = f.search_field :user_email_cont, placeholder: 'User email', class: 'form-control form-control-sm'
        = sort_link(@ransack_courses, :price)
        .row
        = sort_link(@ransack_courses, :average_rating, "Top Rated")
        .row
        = sort_link(@ransack_courses, :enrollments_count, "Most Popular")
        .row
        = sort_link(@ransack_courses, :created_at, "Fresh")
        .row
        = f.submit 
      = link_to @ransack_path, class: 'btn btn-sm btn-secondary' do 
        .fa.fa-sync 
  .col-md-10
    .col-lg-6
      .card-columns 
        - @courses.each do |course|
          = render 'courses/course', course: course 
    -# != pagy_nav(@pagy)
    != pagy_bootstrap_nav(@pagy)

%br

app/views/courses/new.html.haml
- content_for :title do 
  Coursera 
  \|
  New course

.card 
  .card-header
    %h2
      .fa.fa-graduation-cap
      New course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do 
  Coursera 
  \|
  = @course.title

= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p


.row 
  .col-lg-7.order-1.order-lg-1
    .jumbotron 
      %h4 
        .fa.fa-graduation-cap 
        = @course.title 
        .row 
        - if @course.avatar.attached?
          = image_tag @course.avatar, width: "100%";
      .p-3 
      .row 
      .fa.fa-clock 
      = @course.updated_at.strftime("%m/%Y")
      .row 
      .fa.fa-globe-africa 
      = @course.language 
      .row 
      .fa.fa-signal 
      = @course.level
      .p-3 
      = @course.description 

    %h3 
      .fa.fa-tasks
      = pluralize(@course.lessons_count, 'lesson')
      -# = @course.lessons_count 
      -# Lessons:
      .float-right 
        .fa.fa-spinner 
        = number_to_percentage(@course.progress(current_user), precision: 0)
    %ul.list-group.lesson-sortable
      - @lessons.each do |lesson|
        = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson) } do 
          %li.list-group-item
            = render 'lessons/lesson_preview', lesson: lesson
    .p-4

    %h3 
      .fa.fa-comment
      = pluralize(@enrollments_with_review.count, 'review')
      -# Reviews: 
      -# = @enrollments_with_review.count
    - @enrollments_with_review.each do |enrollment|
      = render 'enrollments/enrollment', enrollment: enrollment 
      %p

  .col-lg-5.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
    %p


-# %ul.sortable
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 1
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 2
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 3
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 4
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 5
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 6
-#   %li.ui-state-default
-#     %span.ui-icon.ui-icon-arrowthick-2-n-s>
-#     Item 7