config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  

  resources :enrollments do 
    get :my_students, on: :collection  
  end

  resources :courses do 
    member do 
      get :analytics
      get :approve
      get :unapprove
    end
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    resources :lessons do 
      put :sort
      member do 
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
  end
  resources :users, only: [:index, :edit, :show, :update]

  namespace :charts do 
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  # get 'charts/users_per_day', to: 'charts#users_per_day'
  # get 'charts/enrollments_per_day', to: 'charts#enrollments_per_day'
  # get 'charts/course_popularity', to: 'charts#course_popularity'
  # get 'charts/money_makers', to: 'charts#money_makers'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.haml
%hr 
%footer 
  .container 
    .row 
      .col-md-4 
        Copyright 
        Ⓒ
        = Time.now.year 
        CoursePlatform Sp. z 
        .row 
        .fa.fa-envelope 
        = mail_to 'shadman061@gmail.com'
        .row 
      .col-md-4 
        Privacy policy 
        .row 
        Terms and conditions 
      .col-md-4 
        About us 
        .row 
        = link_to 'Teach on EDURGE', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"} Coursera
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-blod' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do 
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-blod' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do 
            .fa.fa-graduation-cap
            Courses
        .form-inline
          = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
            .input-group 
              = f.search_field :title_cont, class: 'form-control form-control-sm', style: 'float: left; width: 150px'
              %span.input-group-append 
                %button.btn.btn-primary.btn-sm{:type => "submit"}
                  %span.fa.fa-search{"aria-hidden" => "true"}

      %ul.navbar-nav.mr-auto            
        -# %li.nav-item{class: "#{'active font-weight-blod' if current_page?(new_course_path)}"}
        -#   = link_to new_course_path, class: 'nav-link' do 
        -#     .fa.fa-plus
        -#     New Course
        -# %li.nav-item{class: "#{'active font-weight-blod' if current_page?(users_path)}"}
        -#   = link_to users_path, class: 'nav-link' do 
        -#     .fa.fa-users
        -#     Users
        -# %li.nav-item{class: "#{'active font-weight-blod' if current_page?(enrollments_path)}"}
        -#   = link_to enrollments_path, class: 'nav-link' do 
        -#     .fa.fa-lock-open
        -#     Enrollments
        - if current_user.has_role?(:student)
          %li.nav-item.dropdown
            %a#studentDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-graduation-cap
              Learn
            .dropdown-menu.dropdown-meun-right{"aria-labelledby" => "studentDropdown"}
              = link_to purchased_courses_path, class: "dropdown-item" do 
                .fa.fa-graduation-cap
                %b Purchased Courses
                .badge.badge-danger 
                  = current_user.enrollments_count 
              = link_to pending_review_courses_path, class: "dropdown-item" do 
                .fa.fa-star
                %b Pending Review
                .badge.badge-danger 
                  = current_user.enrollments.pending_review.count 

        
        - if current_user.has_role?(:teacher)
          %li.nav-item.dropdown
            %a#teacherDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-chalkboard-teacher
              Teach
            .dropdown-menu.dropdown-meun-right{"aria-labelledby" => "teacherDropdown"}
              = link_to new_course_path, class: "dropdown-item" do 
                .fa.fa-plus
                %b New Course 
              = link_to created_courses_path, class: "dropdown-item" do 
                .fa.fa-graduation-cap
                %b Created courses
                .badge.badge-danger 
                  = current_user.courses_count 
              = link_to my_students_enrollments_path, class: "dropdown-item" do 
                .fa.fa-users
                %b My students
                .badge.badge-danger 
                  = Enrollment.joins(:course).where(courses: {user: current_user}).count 

        - if current_user.has_role?(:admin)
          %li.nav-item.dropdown
            %a#adminDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              .fa.fa-cog
              Admin
            .dropdown-menu.dropdown-meun-right{"aria-labelledby" => "adminDropdown"}
              = link_to unapproved_courses_path, class: "dropdown-item" do 
                .fa.fa-graduation-cap
                %b Unapproved courses
                .badge.badge-danger
                  = Course.unapproved.count 
              = link_to users_path, class: "dropdown-item" do 
                .fa.fa-users
                %b Users 
                .badge.badge-danger 
                  = User.count 
              = link_to enrollments_path, class: "dropdown-item" do 
                .fa.fa-lock-open
                %b Enrollments
                .badge.badge-danger 
                  = Enrollment.count 
              = link_to activity_path, class: "dropdown-item" do 
                .fa.fa-bell
                %b Activity
              = link_to analytics_path, class: "dropdown-item" do 
                .fa.fa-chart-line
                %b Analytics

        
      
      -# .form-inline.my-2.my-lg-0
      -#   = form_tag(courses_path, method: :get) do 
      -#     .input-group 
      -#       = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control'
      -#       %span.input-group-append
      -#         %button.btn.btn-primary.btn-sm{:type => "submit"}
      -#           %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        -# %li.nav-item{class: "#{'active font-weight-blod' if current_page?(activity_path)}"}
          -# = link_to activity_path, class: 'nav-link' do 
          -#   .fa.fa-bell
          -#   Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-meun-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do 
              .fa.fa-cog 
              %b Account settings 
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do 
              .fa.fa-sign-out-alt
              %b Sign out
    -else 
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' 
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

  

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :rol => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ✘ 
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for?(:title) ? yield(:title) : "Coursera"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      %p
      = yield
    %br 
    .bg-dark
      = render 'layouts/footer'